npx remotion render src/index.tsx Party --props='{"ticketName": "Severin Wullschleger\nLaura Fiala"}' out/sevi.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Kyrollos Mansour\nGiulia De Vecci"}' out/kyro.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Marco Stegmaier\nRachel"}' out/marcostegmaier.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Docimo"}' out/docimo.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Francesca Monzeglio"}' out/francesca.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Mehmet Ademi"}' out/mehmetademi.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Till Zellweger"}' out/tillzellweger.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Vivi"}' out/vivi.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Niels Röthlin"}' out/niels.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Dominic Monn"}' out/dominic.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Nathan Keusch"}' out/nathan.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Yasmina Azzaoui"}' out/yasmina.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Raphael Hengartner"}' out/hengi.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Calvin Falter"}' out/calvin.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Andrej Stoy"}' out/andrej.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Sabrina Sakac\nMoris Camporesi"}' out/sabrina.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Daniela Wächter"}' out/daniela.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Nimra Ahmed"}' out/nimra.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Philipp Bachmann + 1"}' out/philippbachmann.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Damiano Robbiano"}' out/damiamo.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Luke Zirngibl"}' out/luke.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Tanja Rothgangl"}' out/tanja.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Chris Herzog"}' out/chrisherzog.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "David Bolli\nJohanna"}' out/davidbolli.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Andreas Lüthi"}' out/andreasluthi.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Bulat Bekhoev"}' out/bulat.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Christoph Schildknecht"}' out/christoph.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Lukas Angst"}' out/lukasangst.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Melke"}' out/melke.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Michael Lehmann"}' out/michaellehmann.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Samuel Berchtold"}' out/samuelberchtold.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Tiziano"}' out/tiziano.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Tobias Frey"}' out/tobiasfrey.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Claudio Gebbia\nNicole"}' out/claudiogebbia.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Remus Nichiteanu + 1"}' out/remus.mp4
npx remotion render src/index.tsx Party --props='{"ticketName": "Piri"}' out/piri.mp4
