/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {Stage, useGLTF} from '@react-three/drei';
import {ThreeCanvas} from '@remotion/three';
import React, {Suspense, useRef} from 'react';
import {useVideoConfig} from 'remotion';
import {Casette} from './Casette';

export const Model = (props) => {
	const {width, height} = useVideoConfig();
	const ref = useRef(null);
	return (
		<ThreeCanvas
			shadows
			width={width}
			height={height}
			dpr={[1, 2]}
			camera={{fov: 50}}
			style={{
				height,
				width,
			}}
		>
			<Suspense fallback={null}>
				<Stage
					controls={ref}
					preset="rembrandt"
					intensity={1}
					environment="city"
				>
					<Casette />
				</Stage>
			</Suspense>
		</ThreeCanvas>
	);
};

useGLTF.preload(
	'https://jonnyburger.s3.eu-central-1.amazonaws.com/casette-full-labeled-v4.glb'
);
